filter_config:
  - selectivity_expectation: 0.1
    selectivity_error: 0.01
    num_filters: 10
    point_portion: 0 # range_portion = 1 - point_portion

  - selectivity_expectation: 0.01
    selectivity_error: 0.001
    num_filters: 10
    point_portion: 0 # range_portion = 1 - point_portion
  
  - selectivity_expectation: 0.001
    selectivity_error: 0.0001
    num_filters: 10
    point_portion: 0 # range_portion = 1 - point_portion

  - selectivity_expectation: 0.0001
    selectivity_error: 0.00001
    num_filters: 10
    point_portion: 0 # range_portion = 1 - point_portion
  
  - selectivity_expectation: 0.00001
    selectivity_error: 0.000001
    num_filters: 30
    point_portion: 0 # range_portion = 1 - point_portion

  - selectivity_expectation: 0.000005
    selectivity_error: 0.0000002
    num_filters: 10
    point_portion: 0 # range_portion = 1 - point_portion

  - selectivity_expectation: 0.000001
    selectivity_error: 0.0000004
    num_filters: 10
    point_portion: 0 # range_portion = 1 - point_portion

  - selectivity_expectation: 0.0000003
    selectivity_error: 0.0000003
    num_filters: 10
    point_portion: 0 # range_portion = 1 - point_portion
    # optional fields: